# Nome del workflow che vedrai nella tab "Actions" di GitHub
name: Deploy to FTP

on:
  push:
    branches:
      - main
  # Aggiungi questa riga per permettere l'avvio manuale
  workflow_dispatch:

jobs:
  # Definiamo un unico job chiamato 'ftp-deploy'
  ftp-deploy:
    # Il tipo di macchina virtuale su cui eseguire il job
    runs-on: ubuntu-latest
    
    steps:
    # 1. Checkout del codice: scarica il codice del tuo repository sulla macchina virtuale
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Deploy FTP: Invia i file al server FTP
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        # Indirizzo del server FTP (es. ftp.tuodominio.com)
        # Legge il valore dal Secret 'FTP_SERVER'
        server: ${{ secrets.FTP_SERVER }}
        
        # Username per l'accesso FTP
        # Legge il valore dal Secret 'FTP_USERNAME'
        username: ${{ secrets.FTP_USERNAME }}
        
        # Password per l'accesso FTP
        # Legge il valore dal Secret 'FTP_PASSWORD'
        password: ${{ secrets.FTP_PASSWORD }}
        
        # Cartella di destinazione sul server FTP (AGGIORNATA)
        server-dir: /httpdocs/wp-content/plugins/statistiche-trello/
